# Generated by Django 5.0.4 on 2024-04-27 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='name',
            new_name='title',
        ),
    ]
