# Generated by Django 5.0.4 on 2024-04-27 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_rename_name_userinfo_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('matchid', models.IntegerField(primary_key=True, serialize=False, verbose_name='赛程ID')),
                ('hostgoal', models.IntegerField(verbose_name='主队分数')),
                ('guestgoal', models.IntegerField(verbose_name='客队分数')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='比赛日期')),
                ('status', models.SmallIntegerField(choices=[(1, '已结束'), (2, '进行中'), (3, '未比赛')], verbose_name='比赛状态')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('playerid', models.IntegerField(primary_key=True, serialize=False, verbose_name='球员ID')),
                ('name', models.CharField(max_length=20, verbose_name='球员名')),
                ('chinaname', models.CharField(max_length=20, verbose_name='球员中文名')),
                ('position', models.CharField(max_length=20, verbose_name='位置')),
                ('nation', models.CharField(max_length=20, verbose_name='国籍')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('prize', models.CharField(max_length=20, verbose_name='身价')),
                ('num', models.IntegerField(verbose_name='号码')),
            ],
        ),
        migrations.CreateModel(
            name='Standings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField(default=0, verbose_name='进球数')),
                ('winlose', models.CharField(max_length=10, verbose_name='胜/平/负')),
                ('points', models.IntegerField(default=0, verbose_name='积分')),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior', models.SmallIntegerField(choices=[(1, 'GOAL'), (2, 'PENALTY'), (3, 'ASSIST'), (4, 'CLEARANCE'), (5, 'TACKLE'), (6, 'REDCARD'), (7, 'YELLOWCARD'), (8, 'OFFSIDE')], verbose_name='球员行为')),
                ('behaviorcount', models.IntegerField(default=0, verbose_name='行为数量')),
                ('matchid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.match')),
                ('playerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamid', models.IntegerField(primary_key=True, serialize=False, verbose_name='球队ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='球队英文名称')),
                ('shortname', models.CharField(max_length=20, verbose_name='球队缩写')),
                ('chinaname', models.CharField(max_length=20, verbose_name='球队中文名称')),
                ('othername', models.CharField(max_length=20, verbose_name='球队中文别名')),
                ('fondtime', models.DateTimeField(auto_now=True, verbose_name='成立时间')),
                ('city', models.CharField(max_length=20, verbose_name='城市')),
                ('home', models.CharField(max_length=20, verbose_name='主场')),
                ('coach', models.CharField(max_length=20, verbose_name='教练')),
            ],
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
        migrations.AddField(
            model_name='standings',
            name='teamid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.team'),
        ),
        migrations.AddField(
            model_name='player',
            name='teamid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='guestteamid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_match', to='world.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='hostteamid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_match', to='world.team'),
        ),
    ]
