# Generated by Django 5.0.4 on 2024-04-27 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_match_player_standings_statistic_team_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='fondtime',
            new_name='foundtime',
        ),
        migrations.AlterField(
            model_name='match',
            name='guestteamid',
            field=models.ForeignKey(db_column='guestteamid', on_delete=django.db.models.deletion.CASCADE, related_name='guest_match', to='world.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='hostteamid',
            field=models.ForeignKey(db_column='hostteamid', on_delete=django.db.models.deletion.CASCADE, related_name='host_match', to='world.team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='teamid',
            field=models.ForeignKey(db_column='teamid', on_delete=django.db.models.deletion.CASCADE, to='world.team'),
        ),
        migrations.AlterField(
            model_name='standings',
            name='teamid',
            field=models.ForeignKey(db_column='teamid', on_delete=django.db.models.deletion.CASCADE, to='world.team'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='matchid',
            field=models.ForeignKey(db_column='matchid', on_delete=django.db.models.deletion.CASCADE, to='world.match'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='playerid',
            field=models.ForeignKey(db_column='playerid', on_delete=django.db.models.deletion.CASCADE, to='world.player'),
        ),
    ]
