# Generated by Django 5.0.4 on 2024-04-27 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0006_rename_fondtime_team_foundtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='teamid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.team'),
        ),
    ]
