# Generated by Django 5.0.4 on 2024-04-27 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0007_alter_player_teamid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='teamid',
            field=models.ForeignKey(db_column='teamid', on_delete=django.db.models.deletion.CASCADE, to='world.team'),
        ),
    ]
