# Generated by Django 5.0.4 on 2024-04-27 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0008_alter_player_teamid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='guestteamid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_match', to='world.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='hostteamid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_match', to='world.team'),
        ),
    ]
