# Generated by Django 5.0.4 on 2024-04-27 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0009_alter_match_guestteamid_alter_match_hostteamid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='guestteamid',
            field=models.ForeignKey(db_column='guestteamid', on_delete=django.db.models.deletion.CASCADE, related_name='guest_match', to='world.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='hostteamid',
            field=models.ForeignKey(db_column='hostteamid', on_delete=django.db.models.deletion.CASCADE, related_name='host_match', to='world.team'),
        ),
    ]
