# Generated by Django 5.0.4 on 2024-04-28 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0010_alter_match_guestteamid_alter_match_hostteamid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='guestteamid',
            field=models.ForeignKey(db_column='guestteamid', on_delete=django.db.models.deletion.CASCADE, related_name='guest_match', to='world.team', verbose_name='客队ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='hostteamid',
            field=models.ForeignKey(db_column='hostteamid', on_delete=django.db.models.deletion.CASCADE, related_name='host_match', to='world.team', verbose_name='主队ID'),
        ),
        migrations.AlterField(
            model_name='player',
            name='teamid',
            field=models.ForeignKey(db_column='teamid', on_delete=django.db.models.deletion.CASCADE, to='world.team', verbose_name='球队ID'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='matchid',
            field=models.ForeignKey(db_column='matchid', on_delete=django.db.models.deletion.CASCADE, to='world.match', verbose_name='赛程ID'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='playerid',
            field=models.ForeignKey(db_column='playerid', on_delete=django.db.models.deletion.CASCADE, to='world.player', verbose_name='球员ID'),
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='球队名')),
                ('sum', models.IntegerField(default=0, verbose_name='场次')),
                ('goals', models.IntegerField(default=0, verbose_name='进球数')),
                ('miss', models.IntegerField(default=0, verbose_name='失球数')),
                ('clear', models.IntegerField(default=0, verbose_name='净胜球')),
                ('points', models.IntegerField(default=0, verbose_name='积分')),
                ('teamid', models.ForeignKey(db_column='teamid', on_delete=django.db.models.deletion.CASCADE, to='world.team', verbose_name='球队ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Standings',
        ),
    ]
