# Generated by Django 5.0.4 on 2024-04-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0011_alter_match_guestteamid_alter_match_hostteamid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standing',
            name='id',
        ),
        migrations.AlterField(
            model_name='standing',
            name='teamid',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='排名'),
        ),
    ]
