# Generated by Django 5.0.4 on 2024-04-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0012_remove_standing_id_alter_standing_teamid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standing',
            name='name',
            field=models.CharField(max_length=40, verbose_name='球队名'),
        ),
    ]
