# Generated by Django 5.0.4 on 2024-04-30 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0015_remove_user_id_alter_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
