# Generated by Django 5.0.4 on 2024-05-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0016_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='standing',
            name='icon_filename',
            field=models.CharField(default='default_icon.png', max_length=30, verbose_name='图标'),
        ),
    ]
